/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "registers.h"
#include "fpu.h"
#include "systick.h"
#include "gpio.h"
#include "usart.h"
#include "dma.h"
#include "tim.h"
#include "tremolo.h"
#include "adc_dac.h"
#include "audio_process.h"

void SystemClock_Init(void);

#define SAMPLE_RATE_HZ 48000U
#define BLOCK_SIZE 256U
static uint16_t adc_ping_buf[BLOCK_SIZE];
static uint16_t adc_pong_buf[BLOCK_SIZE];
static volatile uint8_t adc_frame_ready = 0;
static uint16_t *volatile active_processing_buf = NULL;

void AudioBlock_Ready_Callback(uint16_t *buffer) {
    /* Hand off the filled inactive buffer to the main execution loop */
    active_processing_buf = buffer;
    adc_frame_ready = 1;
}

int main(void)
{
    SystemClock_Init();
    FPU_Init();
    USART3_Init();

    USART3_WriteStr("---------- Reading From POT ----------\r\n");

    /* 1. Pre-arm DMA Stream 0 */
    DMA2_Stream0_ADC_Init(adc_ping_buf, adc_pong_buf, BLOCK_SIZE, AudioBlock_Ready_Callback);

    /* 2. Configure & Power ADC1 (EXTEN = 01, EXTSEL = TIM2 TRGO) */
    Audio_ADC_Init();

    /* 3. Start TIM2 TRGO Heartbeat */
    TIM2_SampleClock_Init(SAMPLE_RATE_HZ);

    /* 1. Read DR to clear EOC, and clear OVR / STRT in SR */
    uint32_t dummy_read = ADC->ADC1.DR;
    ADC->ADC1.SR = 0; /* Clear OVR, EOC, STRT */

    uint32_t block_counter = 0;

    while(1) {
        if (adc_frame_ready) {
            adc_frame_ready = 0; // Clear flag

            if (++block_counter >= 50) {
                block_counter = 0;

                if (active_processing_buf != NULL) {
                    uint16_t raw_val = active_processing_buf[0];
                    uint32_t millivolts = ((uint32_t)raw_val * 3300) / 4095;

                    char str_buf[64];
                    snprintf(str_buf, sizeof(str_buf), "ADC Raw: %u | Volts: %lu.%03luV\r\n",
                             raw_val, millivolts / 1000, millivolts % 1000);
                    USART3_WriteStr(str_buf);
                }
            }
        }
    }
    return 0;
}

void SystemClock_Init(void) {
	RCC->CR |= 1U;
	while(!(RCC->CR&0x2U)) {}
	RCC->APB1ENR |= (1U << 28);
	FLASH->ACR &= ~0x0FU;
	FLASH->ACR |= 0x07U;
	FLASH->ACR |= (1U << 8) | (1U << 9);
	RCC->CFGR &= ~((0x0FU<<4)|(0x07U<<10)|(0x07U<<13));
	RCC->CFGR |= (0x00U<<4)|(0x05U<<10)|(0x04U<<13);
	RCC->PLLCFGR &= ~((0x03FU)|(0x01FFU<<6)|(0x03U<<16)|(0x01U<<22));
	RCC->PLLCFGR |= (8U)|(216U<<6);
	RCC->CR |= (1U<<24);
	while(!(RCC->CR&(1U<<25))) {}
	RCC->CFGR &= ~0x03U;
	RCC->CFGR |= 0x02U;
	while((RCC->CFGR&(0x03U<<2)) != 0x02U<<2) {}
}
