/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "registers.h"
#include "fpu.h"
#include "systick.h"
#include "gpio.h"
#include "usart.h"
#include "dma.h"
#include "tim.h"
#include "tremolo.h"
#include "adc_dac.h"
#include "audio_process.h"

void SystemClock_Init(void);
void Process_cmd(const char *cmd);

#define SAMPLE_RATE_HZ 48000U
#define BLOCK_SIZE 256U
static uint16_t dac_ping_buf[BLOCK_SIZE];
static uint16_t dac_pong_buf[BLOCK_SIZE];
static volatile uint8_t dac_frame_ready = 0;
static uint16_t *volatile available_output_buf = NULL;

void DACBlock_Ready_Callback(uint16_t *buffer) {
    /* The completed inactive DAC buffer is safe for the next DSP result. */
    available_output_buf = buffer;
    dac_frame_ready = 1;
}

int main(void)
{
    SystemClock_Init();
    FPU_Init();
    USART3_Init();
    USART3_WriteStr("Beginning DAC Test/r/n");
    for (uint32_t i = 0; i < BLOCK_SIZE; i++) {
        dac_ping_buf[i] = 2048U;
        dac_pong_buf[i] = 2048U;
    }
    DMA1_Stream5_DAC_Init(dac_ping_buf, dac_pong_buf, BLOCK_SIZE, DACBlock_Ready_Callback);
    Audio_DAC_Init();
    TIM2_SampleClock_Init(SAMPLE_RATE_HZ);
    while(1) {
    	if (dac_frame_ready) {
			dac_frame_ready = 0;

			/* Process 256-sample audio frame in real time */
			if (available_output_buf != NULL) {
				for (int i=0; i<BLOCK_SIZE; i++) {
					available_output_buf[i] = 4090;
				}
			}
		}
    }
    return 0;
}

void SystemClock_Init(void) {
	RCC->CR |= 1U;
	while(!(RCC->CR&0x2U)) {}
	FLASH->ACR &= ~0x0FU;
	FLASH->ACR |= 0x07U;
	FLASH->ACR |= (1U << 8) | (1U << 9);
	RCC->CFGR &= ~((0x0FU<<4)|(0x07U<<10)|(0x07U<<13));
	RCC->CFGR |= (0x00U<<4)|(0x05U<<10)|(0x04U<<13);
	RCC->PLLCFGR &= ~((0x03FU)|(0x01FFU<<6)|(0x03U<<16)|(0x01U<<22));
	RCC->PLLCFGR |= (8U)|(216U<<6);
	RCC->CR |= (1U<<24);
	while(!(RCC->CR&(1U<<25))) {}
	RCC->CFGR &= ~0x03U;
	RCC->CFGR |= 0x02U;
	while((RCC->CFGR&(0x03U<<2)) != 0x02U<<2) {}
}
