name: CFFI DSP Pipeline CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Set up MinGW GCC
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc
          path-type: inherit

      - name: Run PowerShell Test Pipeline
        shell: pwsh
        working-directory: ./Automated Test Harness
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process
          .\run_tests.ps1